services:
  web:
    image: ubuntu:24.04
    container_name: web-server
    ports:
      - "2223:22"
      - "8001:8001"
    tty: true
    command: >
      bash -c "
      apt update &&
      apt install -y git openssh-server wget curl &&
      mkdir /var/run/sshd &&
      echo 'root:' | chpasswd &&
      /usr/sbin/sshd &&
      tail -f /dev/null
      "
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8444:8089"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: B-Eng_Dalin-db
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 256M
      MAX_EXECUTION_TIME: 600
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
