version: '3.8'

services:

  web:
    image: ubuntu:24.04
    container_name: web-server
    ports:
      - "2222:22"
    tty: true
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y git openssh-server wget openjdk-21-jdk maven mysql-client &&
      mkdir -p /var/run/sshd &&
      echo 'root:Hello@123' | chpasswd &&
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
      sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
      mkdir -p /root/.ssh &&
      chmod 700 /root/.ssh &&
      service ssh start &&
      tail -f /dev/null
      "
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8443:8001"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: B-Eng_Dalin-db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: